### ISSUE TITLE
Why all tabs aren't active on the Console Tab?

### ISSUE THREAD

**Issue by mkmaxmk** [pndaproject/red-pnda#19]
When I opened the browser and navigated to the host_ip, there is only title bar.

**Comment by 91pavan** [comment]
Are you running the scripts manually or using the OVA?
Did you manage to run the assign-ip.sh script as specified in the docs?

**Comment by mkmaxmk** [comment]
I uesd the OVA and I did run the assign –ip.  The 8080 port is not available.  The spark web UI is not boot.  I have tried many times.

**Comment by 91pavan** [comment]
Yeah looks like a bug on our side, are the other components available?

**Comment by mkmaxmk** [comment]
yes  other components are available

**Comment by 91pavan** [comment]
Can you download the new OVA which includes the fix and give it a try? http://d5zjefk3wzew6.cloudfront.net/Red_PNDA-0.2.3.ova

Thank you.

**Comment by 91pavan** [comment]
Or if you prefer to edit the scripts to get the spark webUI, follow these steps:

    sudo su
    #edit the crontab
    crontab -e

Edit this line and replace with the appropriate values, I think `$SPARK_HOME` is `/usr/local/spark` in your case so replace those values:

    @reboot $SPARK_HOME/start-master.sh && $SPARK_HOME/sbin/start-slave.sh spark://red-pnda:7077

And reboot once for these changes to take effect.

**Comment by mkmaxmk** [comment]
Hello,  I tried the new OVA and the Spark webUI is fixed. However, the http://192.168.56.101/#/  is still only have title bar.  
![22](https://user-images.githubusercontent.com/9927205/32876086-3169bd0e-cad6-11e7-91bf-b569ca70d7b9.PNG)

**Comment by 91pavan** [comment]
I'm really unable to second guess what the problem could be, can you please paste the output of `ifconfig` command? Are you running this on VirtualBox or on Fusion?
What's the version number?

Also, it would be great if you look at the logs at `/var/log/upstart` and see if something is throwing an error.

**Comment by mkmaxmk** [comment]
Thank you for you reply patiently.  This is the ifconfig output.  
![3](https://user-images.githubusercontent.com/9927205/32885682-2b808f9e-caf9-11e7-8591-4fabcc6d7fff.PNG)

Which log should I see?

![4](https://user-images.githubusercontent.com/9927205/32885692-31d148e8-caf9-11e7-92b3-afc6b86805b9.PNG)

**Comment by mkmaxmk** [comment]
I find in ureadahead.log throw lots of errors:

![6](https://user-images.githubusercontent.com/9927205/32885938-119857a0-cafa-11e7-9806-a56cd431acdc.PNG)

**Comment by 91pavan** [comment]
`ureadahead.log` is not relevant I think. Can you run `ls -ltr` and tail few logs which are last modified and see if they are throwing some error?

Also run:

    sudo bash /home/pnda/assign-ip.sh eth0

**Comment by mkmaxmk** [comment]
Thank you. It's work now.   When  I run   " bash assign-ip.sh eth0   " , it is ok .    But  when I run "sh assign-ip.sh eth0" in the docs say, it dosen't work.

**Comment by 91pavan** [comment]
Ok, no problem. Glad it worked ok. Just updated the docs, thank you. Closing the issue.
