### ISSUE TITLE
kafka file not found error 404 while running install dependencies command 

### ISSUE THREAD

**Issue by divyas7** [pndaproject/red-pnda#20]
installing kafka..
--2017-11-20 09:13:42--  http://apache.mirror.anlx.net/kafka/0.10.2.1/kafka_2.11-0.10.2.0.tgz
Resolving apache.mirror.anlx.net (apache.mirror.anlx.net)... 81.91.108.244
Connecting to apache.mirror.anlx.net (apache.mirror.anlx.net)|81.91.108.244|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-11-20 09:13:45 ERROR 404: Not Found.

Please let me know what to do.. the kafka version file is not there in the server

**Comment by trsmith2** [comment]
Please provide a description of what file is causing the problem.

**Comment by divyas7** [comment]
installing kafka..
--2017-11-20 09:13:42-- http://apache.mirror.anlx.net/kafka/0.10.2.1/kafka_2.11-0.10.2.0.tgz
Resolving apache.mirror.anlx.net (apache.mirror.anlx.net)... 81.91.108.244
Connecting to apache.mirror.anlx.net (apache.mirror.anlx.net)|81.91.108.244|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-11-20 09:13:45 ERROR 404: Not Found.

**Comment by trsmith2** [comment]
Right, the mirror should be http://archive.apache.org/dist/kafka/. Would you mind raising a PR to fix this?

**Comment by 91pavan** [comment]
Just pushed an update which should fix the problem.
@divyas7 can you pull and run the scripts again? Thanks

**Comment by 91pavan** [comment]
Closing the issue, please reopen if this error persists
