### ISSUE TITLE
red-pnda installation stopped abruptly

### ISSUE THREAD

**Issue by divyas7** [pndaproject/red-pnda#22]
![redpnda error](https://user-images.githubusercontent.com/32533896/34976042-b522dd6a-faba-11e7-9d43-436a5caf5960.JPG)
 trying to install red-pnda on AWS ubuntu 14.0.4 server and its stopping by saying some authentication problem in npm. I found a fix in google and the installation was successful but its asking username and password to view the console . Please let me know what to do

**Comment by trsmith2** [comment]
The Console uses PAM to authenticate so log in using a user present on the edge node.
